### ISSUE TITLE
无法使用指令

### ISSUE THREAD

**Issue by qcbby** [Mcayear/AMCBuilder#1]
在最新版中只可以使用/amcb 查看帮助
/amcb pos1
/amcb pos2等指令都无法使用

**Comment by Mcayear** [comment]
经过测试PNX版本可以正常使用
/amcb pos1
/amcb pos2
![Uploading Screenshot_20230212_134237.jpg…]()

**Comment by qcbby** [comment]
那我重新试试看

**Comment by Mcayear** [comment]
![Screenshot_20230212_134237](https://user-images.githubusercontent.com/48203962/218295624-b2a004c1-9ae8-4795-aadb-7b89af8b6816.jpg)

**Comment by qcbby** [comment]
不过我还是用不了
![Uploading Screenshot_2023-02-12-14-06-51-664_com.mojang.minecraftpe.jpg…]()

**Comment by qcbby** [comment]
LiteLoaderLibs是最新版0.0.3
pnx最新版
AMCBuilder是从仓库下载的
不过就是用不了

**Comment by Mcayear** [comment]
你发的图片无法查看
![image](https://user-images.githubusercontent.com/48203962/219932506-8beb31d0-24bc-4314-81e9-b79f26a0e444.png)
